USE customer_behaviour;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS total_revenue
FROM
    customer_data
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount, discount_applied
FROM
    customer_data
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_rating
FROM
    customer_data
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customer_data
GROUP BY shipping_type
HAVING shipping_type IN ('Express' , 'Standard');



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    SUM(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS revenue
FROM
    customer_data
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case when previous_purchases = 1 then "New"
	when previous_purchases between 2 and 5 then "Returning"
    else "Loyal"
    end as customer_segment
    from customer_data
)
select customer_segment, count(*) as total_customer from customer_type
group by customer_segment
;


-- Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc )as item_rank
from customer_data
group by category,item_purchased
)
select item_rank,item_purchased,category,total_orders
from item_count
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, COUNT(customer_id) AS total_customer
FROM
    customer_data
WHERE
    previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS revenue_contri
FROM
    customer_data
GROUP BY age_group;